# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiseTestGo < Formula
  desc "Testing mise go and github backends"
  homepage "https://github.com/nathforge/mise-test-go"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nathforge/mise-test-go/releases/download/v0.3.0/mise-test-go_darwin_amd64.tar.gz"
      sha256 "ddbe6f0574b92e7f031cc0359130a00280242514195310cf645d26d478c9f090"

      define_method(:install) do
        bin.install "mise-test-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nathforge/mise-test-go/releases/download/v0.3.0/mise-test-go_darwin_arm64.tar.gz"
      sha256 "c3a9fc1b5780d15790f23f6c1e332b8d3b179d9b960a1a08ad108ccba6bf9a07"

      define_method(:install) do
        bin.install "mise-test-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nathforge/mise-test-go/releases/download/v0.3.0/mise-test-go_linux_amd64.tar.gz"
      sha256 "e191b053a8f4f84724edcb2a7539a8bac3b213391ef75129aeade15a30ae3405"
      define_method(:install) do
        bin.install "mise-test-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nathforge/mise-test-go/releases/download/v0.3.0/mise-test-go_linux_arm64.tar.gz"
      sha256 "5d1e3b5da10b37e54c95cdf1c857a1e2a8d19ca7a7e9321a18b2bb199e96103b"
      define_method(:install) do
        bin.install "mise-test-go"
      end
    end
  end
end
