# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiseTestGo < Formula
  desc "Testing mise go and github backends"
  homepage "https://github.com/nathforge/mise-test-go"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nathforge/mise-test-go/releases/download/v0.3.0/mise-test-go_darwin_amd64.tar.gz"
      sha256 "3eb30882d24aea65a85982f361547971cc4229cac3b6be4ff8b615a9a68be22d"

      define_method(:install) do
        bin.install "mise-test-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nathforge/mise-test-go/releases/download/v0.3.0/mise-test-go_darwin_arm64.tar.gz"
      sha256 "606ac44b041c5996db16b2aa8af80c3203660d7c19e4d292630ede5535bebd5f"

      define_method(:install) do
        bin.install "mise-test-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nathforge/mise-test-go/releases/download/v0.3.0/mise-test-go_linux_amd64.tar.gz"
      sha256 "2bc8ad634935c61df14f94e46883c75af122c2a8c06b208f7b45d516a562aeef"
      define_method(:install) do
        bin.install "mise-test-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nathforge/mise-test-go/releases/download/v0.3.0/mise-test-go_linux_arm64.tar.gz"
      sha256 "06aef47b82f30e8b28497def3c57fd0fd7f6d3bde1865f797821301f544960af"
      define_method(:install) do
        bin.install "mise-test-go"
      end
    end
  end
end
