# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiseTestPython < Formula
  desc "Testing mise pipx and github backends"
  homepage "https://github.com/nathforge/mise-test-python"
  version "2.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nathforge/mise-test-python/releases/download/v2.0.0/mise-test-python_darwin_arm64.tar.gz"
      sha256 "cde738de3e60eeb313a027a1b2baab7801a8a3d09c2ff6223cd972ed452cffd9"

      define_method(:install) do
        bin.install "mise-test-python"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nathforge/mise-test-python/releases/download/v2.0.0/mise-test-python_linux_amd64.tar.gz"
      sha256 "fc288dedd92ed0843f506d6253979319a7ededd5b5e26e162158ec9cf800dd1f"
      define_method(:install) do
        bin.install "mise-test-python"
      end
    end
  end
end
